### PR TITLE
STL tests (unit+performance)

### PR DESCRIPTION
**Pull request by droccom**

### CODE REVIEW

**Comment by mminutoli** [comment]
The build is failinig

https://travis-ci.org/pnnl/SHAD/jobs/411527354

**Comment by mminutoli** [comment]
@droccom Do you know how to rewrite the history to change the commit tag?

**Comment by mminutoli** [comment]
OK, whatever.  Just fix the build and we will merge to master.

**Comment by droccom** [comment]
Merging PR #84should fix the build issue.

**Comment by droccom** [comment]
Now passing the build.

**Pull request merged**
